# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 367934ebb9ebd1c08795209223555756e6a87b2303e8cada53f3ea7c4ec0762cbe5e7b410772d9bd2e4d87911957c78e76bafd1e129f8d89d5578e638e5f208a

test:
  secret_key_base: fc1d7ea7269b5caf8fb8df6155956be0f70ad0c546389a0234ca4ff4dfc47d876fde24e45a4946c5434a45e797179f40a047479161e2aad3b12b7a766d87a2ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
